version: "3.9"

services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gisdb
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: fastapi_service
    depends_on:
      - postgis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgis:5432/gisdb
    ports:
      - "8000:8000"
    command: uv run uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload


volumes:
  postgis_data: