[project]
name = "data-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "geoalchemy2>=0.17.0",
    "pydantic>=2.10.6",
    "ruff>=0.9.4",
    "shapely>=2.0.7",
    "sqlmodel>=0.0.22",
]
